In [39]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
import pandas as pd

In [32]:
corpus = [
    "students watch youtube youtube youtube",
    "youtube watch youtube",
    "students write comments",
    "youtube write comments"
]

#### Create bag of words model

In [33]:
cv = CountVectorizer(ngram_range=(1,3))

In [34]:
X = cv.fit_transform(corpus)

In [35]:
cv.get_feature_names_out()

array(['comments', 'students', 'students watch', 'students watch youtube',
       'students write', 'students write comments', 'watch',
       'watch youtube', 'watch youtube youtube', 'write',
       'write comments', 'youtube', 'youtube watch',
       'youtube watch youtube', 'youtube write', 'youtube write comments',
       'youtube youtube', 'youtube youtube youtube'], dtype=object)

In [36]:
X.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 3, 0, 0, 0, 0, 2, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0]])

In [37]:
bow_df = pd.DataFrame(
    X.toarray(),
    columns= cv.get_feature_names_out(),
    index= ["D1","D2","D3","D4"]
)

In [38]:
bow_df

,comments,students,students watch,students watch youtube,students write,students write comments,watch,watch youtube,watch youtube youtube,write,write comments,youtube,youtube watch,youtube watch youtube,youtube write,youtube write comments,youtube youtube,youtube youtube youtube
D1,0,1,1,1,0,0,1,1,1,0,0,3,0,0,0,0,2,1
D2,0,0,0,0,0,0,1,1,0,0,0,2,1,1,0,0,0,0
D3,1,1,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0
D4,1,0,0,0,0,0,0,0,0,1,1,1,0,0,1,1,0,0

##### Tf-idf

In [41]:
df = pd.DataFrame(
    {
        "text":corpus,
        "output":[1,1,0,0]
    }
)
df

                                     text  output
0  students watch youtube youtube youtube       1
1                   youtube watch youtube       1
2                 students write comments       0
3                  youtube write comments       0

In [42]:
tfidf =TfidfVectorizer()
X = tfidf.fit_transform(df['text'])

In [43]:
tfidf_df = pd.DataFrame(
    X.toarray(),
    columns = tfidf.get_feature_names_out()
)

In [44]:
tfidf_df

   comments  students     watch     write   youtube
0  0.000000   0.35581  0.355810  0.000000  0.864175
1  0.000000   0.00000  0.525464  0.000000  0.850816
2  0.577350   0.57735  0.000000  0.577350  0.000000
3  0.613667   0.00000  0.000000  0.613667  0.496816

In [45]:
tfidf.vocabulary_

{'students': 1, 'watch': 2, 'youtube': 4, 'write': 3, 'comments': 0}