In [3]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
import torch

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [5]:
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [29]:
df.isna().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [13]:
try:
    df = df.drop(columns=['Unnamed: 32','id'])
except:
    pass

In [17]:
df.describe().T

                         count        mean  ...          75%         max
radius_mean              569.0   14.127292  ...    15.780000    28.11000
texture_mean             569.0   19.289649  ...    21.800000    39.28000
perimeter_mean           569.0   91.969033  ...   104.100000   188.50000
area_mean                569.0  654.889104  ...   782.700000  2501.00000
smoothness_mean          569.0    0.096360  ...     0.105300     0.16340
compactness_mean         569.0    0.104341  ...     0.130400     0.34540
concavity_mean           569.0    0.088799  ...     0.130700     0.42680
concave points_mean      569.0    0.048919  ...     0.074000     0.20120
symmetry_mean            569.0    0.181162  ...     0.195700     0.30400
fractal_dimension_mean   569.0    0.062798  ...     0.066120     0.09744
radius_se                569.0    0.405172  ...     0.478900     2.87300
texture_se               569.0    1.216853  ...     1.474000     4.88500
perimeter_se             569.0    2.866059  ...     3.357000    21.98000
area_se                  569.0   40.337079  ...    45.190000   542.20000
smoothness_se            569.0    0.007041  ...     0.008146     0.03113
compactness_se           569.0    0.025478  ...     0.032450     0.13540
concavity_se             569.0    0.031894  ...     0.042050     0.39600
concave points_se        569.0    0.011796  ...     0.014710     0.05279
symmetry_se              569.0    0.020542  ...     0.023480     0.07895
fractal_dimension_se     569.0    0.003795  ...     0.004558     0.02984
radius_worst             569.0   16.269190  ...    18.790000    36.04000
texture_worst            569.0   25.677223  ...    29.720000    49.54000
perimeter_worst          569.0  107.261213  ...   125.400000   251.20000
area_worst               569.0  880.583128  ...  1084.000000  4254.00000
smoothness_worst         569.0    0.132369  ...     0.146000     0.22260
compactness_worst        569.0    0.254265  ...     0.339100     1.05800
concavity_worst          569.0    0.272188  ...     0.382900     1.25200
concave points_worst     569.0    0.114606  ...     0.161400     0.29100
symmetry_worst           569.0    0.290076  ...     0.317900     0.66380
fractal_dimension_worst  569.0    0.083946  ...     0.092080     0.20750

[30 rows x 8 columns]

In [19]:
df.describe(exclude=np.number).T

          count unique top freq
diagnosis   569      2   B  357

In [20]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [30]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=.2,random_state=42,stratify=df['diagnosis'])

In [42]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [43]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [46]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [48]:
X_train_tensor.shape

torch.Size([455, 30])

###### Define the model

In [72]:
class MySimpleNN():
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self,y,y_pred):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
        loss = -((y*torch.log(y_pred)) + (1-y)*torch.log(1-y_pred)).mean()
        return loss

In [75]:
model = MySimpleNN(X_train_tensor)

for epoch in range(100):
    y_pred = model.forward(X_train_tensor)
    loss = model.loss_function(y_train_tensor,y_pred)
    loss.backward()
    with torch.no_grad():
        model.weights -= .1*model.weights.grad
        model.bias -= .1*model.bias.grad

    model.weights.grad.zero_()
    model.bias.grad.zero_()
    print(f"Epoch: {epoch+1}, Loss = {loss.item()}")

Epoch: 1, Loss = 3.927393423720917
Epoch: 2, Loss = 3.819477276180872
Epoch: 3, Loss = 3.705570107657954
Epoch: 4, Loss = 3.582133996440964
Epoch: 5, Loss = 3.4550214051329218
Epoch: 6, Loss = 3.325819162413969
Epoch: 7, Loss = 3.1882153621293003
Epoch: 8, Loss = 3.0474336590218223
Epoch: 9, Loss = 2.9025883683676454
Epoch: 10, Loss = 2.755717691435205
Epoch: 11, Loss = 2.6078107341716845
Epoch: 12, Loss = 2.4531385148171956
Epoch: 13, Loss = 2.2925964523878757
Epoch: 14, Loss = 2.132503830027618
Epoch: 15, Loss = 1.977484768501955
Epoch: 16, Loss = 1.8214842905427953
Epoch: 17, Loss = 1.669147497853005
Epoch: 18, Loss = 1.522592389872952
Epoch: 19, Loss = 1.3880758317271749
Epoch: 20, Loss = 1.2642988067317058
Epoch: 21, Loss = 1.1564417464308172
Epoch: 22, Loss = 1.0652864324021178
Epoch: 23, Loss = 0.99078980170512
Epoch: 24, Loss = 0.9319266715970637
Epoch: 25, Loss = 0.8867643555189346
Epoch: 26, Loss = 0.8527949966150664
Epoch: 27, Loss = 0.8273842066335205
Epoch: 28, Loss = 0.808158414138399
Epoch: 29, Loss = 0.7932285675510334
Epoch: 30, Loss = 0.7812343464128119
Epoch: 31, Loss = 0.7712652997976394
Epoch: 32, Loss = 0.762738558399221
Epoch: 33, Loss = 0.7552870097380838
Epoch: 34, Loss = 0.7486771082104045
Epoch: 35, Loss = 0.7427552553137708
Epoch: 36, Loss = 0.7374151853575687
Epoch: 37, Loss = 0.7325789268500584
Epoch: 38, Loss = 0.7281859265357301
Epoch: 39, Loss = 0.7241868750074965
Epoch: 40, Loss = 0.720540172573256
Epoch: 41, Loss = 0.7172098587321026
Epoch: 42, Loss = 0.7141643509521535
Epoch: 43, Loss = 0.7113756343944484
Epoch: 44, Loss = 0.7088187075660023
Epoch: 45, Loss = 0.7064711775837191
Epoch: 46, Loss = 0.704312946520703
Epoch: 47, Loss = 0.7023259560614957
Epoch: 48, Loss = 0.7004939716880624
Epoch: 49, Loss = 0.6988023953406971
Epoch: 50, Loss = 0.6972380998440235
Epoch: 51, Loss = 0.6957892808839065
Epoch: 52, Loss = 0.6944453237779334
Epoch: 53, Loss = 0.693196683141182
Epoch: 54, Loss = 0.6920347740573608
Epoch: 55, Loss = 0.6909518736664226
Epoch: 56, Loss = 0.6899410322588099
Epoch: 57, Loss = 0.6889959930754291
Epoch: 58, Loss = 0.688111120082645
Epoch: 59, Loss = 0.6872813330417737
Epoch: 60, Loss = 0.6865020492334833
Epoch: 61, Loss = 0.6857691312349962
Epoch: 62, Loss = 0.6850788401848119
Epoch: 63, Loss = 0.6844277940068701
Epoch: 64, Loss = 0.683812930103733
Epoch: 65, Loss = 0.6832314720661163
Epoch: 66, Loss = 0.6826808999833782
Epoch: 67, Loss = 0.6821589239758469
Epoch: 68, Loss = 0.68166346060467
Epoch: 69, Loss = 0.6811926118478149
Epoch: 70, Loss = 0.680744646361725
Epoch: 71, Loss = 0.6803179827767729
Epoch: 72, Loss = 0.679911174801006
Epoch: 73, Loss = 0.6795228979307604
Epoch: 74, Loss = 0.6791519375885996
Epoch: 75, Loss = 0.6787971785288044
Epoch: 76, Loss = 0.6784575953684276
Epoch: 77, Loss = 0.6781322441178915
Epoch: 78, Loss = 0.6778202545993568
Epoch: 79, Loss = 0.6775208236538154
Epoch: 80, Loss = 0.6772332090491682
Epoch: 81, Loss = 0.6769567240115938
Epoch: 82, Loss = 0.6766907323114292
Epoch: 83, Loss = 0.6764346438426683
Epoch: 84, Loss = 0.6761879106421693
Epoch: 85, Loss = 0.6759500233008379
Epoch: 86, Loss = 0.6757205077245051
Epoch: 87, Loss = 0.6754989222070409
Epoch: 88, Loss = 0.6752848547825008
Epoch: 89, Loss = 0.6750779208268629
Epoch: 90, Loss = 0.6748777608832263
Epoch: 91, Loss = 0.6746840386872814
Epoch: 92, Loss = 0.6744964393724423
Epoch: 93, Loss = 0.674314667836324
Epoch: 94, Loss = 0.6741384472522687
Epoch: 95, Loss = 0.6739675177114074
Epoch: 96, Loss = 0.6738016349823308
Epoch: 97, Loss = 0.6736405693768316
Epoch: 98, Loss = 0.6734841047114327
Epoch: 99, Loss = 0.6733320373554981
Epoch: 100, Loss = 0.6731841753577064

In [86]:
with torch.no_grad():
    y_pred = model.forward(X_train_tensor)
    y_pred = (y_pred>.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(accuracy.item())

0.6315789222717285